### ISSUE TITLE
No internet connection when sign in with google even if mobile connected to internert

### ISSUE THREAD

**Issue by AyaAbouebeid** [basmaseyam/flutter-groccery-list#67]
when running the app and try to log in by google, error message appears that there is no internet connection even if internet is working user should wait till error message timer end to be loged in to app out click out the focus
both cases user enter the app with no loged account

https://user-images.githubusercontent.com/67022405/170823659-4560ce9d-4a99-4b53-ba99-091d7bfbf494.mp4

**Comment by basmaseyam** [comment]
Can't reproduce the issue it's working fine with me. try to run flutter pub get and check it
